// GENERATED by tools/spec_tool.py from the exam board's own specification.
// Do not edit by hand: run `python tools/spec_tool.py generate` instead.
// Source: https://www.aqa.org.uk/subjects/biology/gcse/biology-8461/specification/subject-content
// Checked: 2026-09-20

package revision.core.catalogue.aqa

import revision.core.catalogue.Board
import revision.core.catalogue.SpecGroup
import revision.core.catalogue.SpecSubject
import revision.core.catalogue.SpecTopic

val aqaBiology: SpecSubject = SpecSubject(
    key = "biology",
    ref = "aqa/biology-8461",
    board = Board.AQA,
    name = "Biology",
    specCode = "8461",
    sourceUrl = "https://www.aqa.org.uk/subjects/biology/gcse/biology-8461/specification/subject-content",
    checkedOn = "2026-09-20",
    groups = listOf(
        SpecGroup(
            code = "4.1",
            title = "Cell biology",
            topics = listOf(
                SpecTopic("4.1.1", "Cell structure"),
                SpecTopic("4.1.2", "Cell division"),
                SpecTopic("4.1.3", "Transport in cells"),
            ),
        ),
        SpecGroup(
            code = "4.2",
            title = "Organisation",
            topics = listOf(
                SpecTopic("4.2.1", "Principles of organisation"),
                SpecTopic("4.2.2", "Animal tissues, organs and organ systems"),
                SpecTopic("4.2.3", "Plant tissues, organs and systems"),
            ),
        ),
        SpecGroup(
            code = "4.3",
            title = "Infection and response",
            topics = listOf(
                SpecTopic("4.3.1", "Communicable diseases"),
                SpecTopic("4.3.2", "Monoclonal antibodies (biology only) (HT only)"),
                SpecTopic("4.3.3", "Plant disease (biology only)"),
            ),
        ),
        SpecGroup(
            code = "4.4",
            title = "Bioenergetics",
            topics = listOf(
                SpecTopic("4.4.1", "Photosynthesis"),
                SpecTopic("4.4.2", "Respiration"),
            ),
        ),
        SpecGroup(
            code = "4.5",
            title = "Homeostasis and response",
            topics = listOf(
                SpecTopic("4.5.1", "Homeostasis"),
                SpecTopic("4.5.2", "The human nervous system"),
                SpecTopic("4.5.3", "Hormonal coordination in humans"),
                SpecTopic("4.5.4", "Plant hormones (biology only)"),
            ),
        ),
        SpecGroup(
            code = "4.6",
            title = "Inheritance, variation and evolution",
            topics = listOf(
                SpecTopic("4.6.1", "Reproduction"),
                SpecTopic("4.6.2", "Variation and evolution"),
                SpecTopic("4.6.3", "The development of understanding of genetics and evolution"),
                SpecTopic("4.6.4", "Classification of living organisms"),
            ),
        ),
        SpecGroup(
            code = "4.7",
            title = "Ecology",
            topics = listOf(
                SpecTopic("4.7.1", "Adaptations, interdependence and competition"),
                SpecTopic("4.7.2", "Organisation of an ecosystem"),
                SpecTopic("4.7.3", "Biodiversity and the effect of human interaction on ecosystems"),
                SpecTopic("4.7.4", "Trophic levels in an ecosystem (biology only)"),
                SpecTopic("4.7.5", "Food production (biology only)"),
            ),
        ),
        SpecGroup(
            code = "4.8",
            title = "Key ideas",
            topics = listOf(
                SpecTopic("4.8", "Key ideas"),
            ),
        ),
    ),
)
