// GENERATED by tools/spec_tool.py from the exam board's own specification.
// Do not edit by hand: run `python tools/spec_tool.py generate` instead.
// Source: https://www.aqa.org.uk/subjects/chemistry/gcse/chemistry-8462/specification/subject-content
// Checked: 2026-09-20

package revision.core.catalogue.aqa

import revision.core.catalogue.Board
import revision.core.catalogue.SpecGroup
import revision.core.catalogue.SpecSubject
import revision.core.catalogue.SpecTopic

val aqaChemistry: SpecSubject = SpecSubject(
    key = "chemistry",
    ref = "aqa/chemistry-8462",
    board = Board.AQA,
    name = "Chemistry",
    specCode = "8462",
    sourceUrl = "https://www.aqa.org.uk/subjects/chemistry/gcse/chemistry-8462/specification/subject-content",
    checkedOn = "2026-09-20",
    groups = listOf(
        SpecGroup(
            code = "4.1",
            title = "Atomic structure and the periodic table",
            topics = listOf(
                SpecTopic("4.1.1", "A simple model of the atom, symbols, relative atomic mass, electronic charge and isotopes"),
                SpecTopic("4.1.2", "The periodic table"),
                SpecTopic("4.1.3", "Properties of transition metals (chemistry only)"),
            ),
        ),
        SpecGroup(
            code = "4.2",
            title = "Bonding, structure, and the properties of matter",
            topics = listOf(
                SpecTopic("4.2.1", "Chemical bonds, ionic, covalent and metallic"),
                SpecTopic("4.2.2", "How bonding and structure are related to the properties of substances"),
                SpecTopic("4.2.3", "Structure and bonding of carbon"),
                SpecTopic("4.2.4", "Bulk and surface properties of matter including nanoparticles (chemistry only)"),
            ),
        ),
        SpecGroup(
            code = "4.3",
            title = "Quantitative chemistry",
            topics = listOf(
                SpecTopic("4.3.1", "Chemical measurements, conservation of mass and the quantitative interpretation of chemical equations"),
                SpecTopic("4.3.2", "Use of amount of substance in relation to masses of pure substances"),
                SpecTopic("4.3.3", "Yield and atom economy of chemical reactions (chemistry only)"),
                SpecTopic("4.3.4", "Using concentrations of solutions in mol/dm 3 (chemistry only) (HT only)"),
                SpecTopic("4.3.5", "Use of amount of substance in relation to volumes of gases (chemistry only) (HT only)"),
            ),
        ),
        SpecGroup(
            code = "4.4",
            title = "Chemical changes",
            topics = listOf(
                SpecTopic("4.4.1", "Reactivity of metals"),
                SpecTopic("4.4.2", "Reactions of acids"),
                SpecTopic("4.4.3", "Electrolysis"),
            ),
        ),
        SpecGroup(
            code = "4.5",
            title = "Energy changes",
            topics = listOf(
                SpecTopic("4.5.1", "Exothermic and endothermic reactions"),
                SpecTopic("4.5.2", "Chemical cells and fuel cells (chemistry only)"),
            ),
        ),
        SpecGroup(
            code = "4.6",
            title = "The rate and extent of chemical change",
            topics = listOf(
                SpecTopic("4.6.1", "Rate of reaction"),
                SpecTopic("4.6.2", "Reversible reactions and dynamic equilibrium"),
            ),
        ),
        SpecGroup(
            code = "4.7",
            title = "Organic chemistry",
            topics = listOf(
                SpecTopic("4.7.1", "Carbon compounds as fuels and feedstock"),
                SpecTopic("4.7.2", "Reactions of alkenes and alcohols (chemistry only)"),
                SpecTopic("4.7.3", "Synthetic and naturally occurring polymers (chemistry only)"),
            ),
        ),
        SpecGroup(
            code = "4.8",
            title = "Chemical analysis",
            topics = listOf(
                SpecTopic("4.8.1", "Purity, formulations and chromatography"),
                SpecTopic("4.8.2", "Identification of common gases"),
                SpecTopic("4.8.3", "Identification of ions by chemical and spectroscopic means (chemistry only)"),
            ),
        ),
        SpecGroup(
            code = "4.9",
            title = "Chemistry of the atmosphere",
            topics = listOf(
                SpecTopic("4.9.1", "The composition and evolution of the Earth's atmosphere"),
                SpecTopic("4.9.2", "Carbon dioxide and methane as greenhouse gases"),
                SpecTopic("4.9.3", "Common atmospheric pollutants and their sources"),
            ),
        ),
        SpecGroup(
            code = "4.10",
            title = "Using resources",
            topics = listOf(
                SpecTopic("4.10.1", "Using the Earth's resources and obtaining potable water"),
                SpecTopic("4.10.2", "Life cycle assessment and recycling"),
                SpecTopic("4.10.3", "Using materials (chemistry only)"),
                SpecTopic("4.10.4", "The Haber process and the use of NPK fertilisers (chemistry only)"),
            ),
        ),
        SpecGroup(
            code = "4.11",
            title = "Key ideas",
            topics = listOf(
                SpecTopic("4.11", "Key ideas"),
            ),
        ),
    ),
)
