// GENERATED by tools/spec_tool.py from the exam board's own specification.
// Do not edit by hand: run `python tools/spec_tool.py generate` instead.
// Source: https://www.aqa.org.uk/subjects/computer-science/gcse/computer-science-8525/specification/subject-content
// Checked: 2026-09-20

package revision.core.catalogue.aqa

import revision.core.catalogue.Board
import revision.core.catalogue.SpecGroup
import revision.core.catalogue.SpecSubject
import revision.core.catalogue.SpecTopic

val aqaComputerScience: SpecSubject = SpecSubject(
    key = "computer-science",
    ref = "aqa/computer-science-8525",
    board = Board.AQA,
    name = "Computer Science",
    specCode = "8525",
    sourceUrl = "https://www.aqa.org.uk/subjects/computer-science/gcse/computer-science-8525/specification/subject-content",
    checkedOn = "2026-09-20",
    groups = listOf(
        SpecGroup(
            code = "3.1",
            title = "Fundamentals of algorithms",
            topics = listOf(
                SpecTopic("3.1.1", "Representing algorithms"),
                SpecTopic("3.1.2", "Efficiency of algorithms"),
                SpecTopic("3.1.3", "Searching algorithms"),
                SpecTopic("3.1.4", "Sorting algorithms"),
            ),
        ),
        SpecGroup(
            code = "3.2",
            title = "Programming",
            topics = listOf(
                SpecTopic("3.2.1", "Data types"),
                SpecTopic("3.2.2", "Programming concepts"),
                SpecTopic("3.2.3", "Arithmetic operations in a programming language"),
                SpecTopic("3.2.4", "Relational operations in a programming language"),
                SpecTopic("3.2.5", "Boolean operations in a programming language"),
                SpecTopic("3.2.6", "Data structures"),
                SpecTopic("3.2.7", "Input/output"),
                SpecTopic("3.2.8", "String handling operations in a programming language"),
                SpecTopic("3.2.9", "Random number generation in a programming language"),
                SpecTopic("3.2.10", "Structured programming and subroutines (procedures and functions)"),
                SpecTopic("3.2.11", "Robust and secure programming"),
            ),
        ),
        SpecGroup(
            code = "3.3",
            title = "Fundamentals of data representation",
            topics = listOf(
                SpecTopic("3.3.1", "Number bases"),
                SpecTopic("3.3.2", "Converting between number bases"),
                SpecTopic("3.3.3", "Units of information"),
                SpecTopic("3.3.4", "Binary arithmetic"),
                SpecTopic("3.3.5", "Character encoding"),
                SpecTopic("3.3.6", "Representing images"),
                SpecTopic("3.3.7", "Representing sound"),
                SpecTopic("3.3.8", "Data compression"),
            ),
        ),
        SpecGroup(
            code = "3.4",
            title = "Computer systems",
            topics = listOf(
                SpecTopic("3.4.1", "Hardware and software"),
                SpecTopic("3.4.2", "Boolean logic"),
                SpecTopic("3.4.3", "Software classification"),
                SpecTopic("3.4.4", "Classification of programming languages and translators"),
                SpecTopic("3.4.5", "Systems architecture"),
            ),
        ),
        SpecGroup(
            code = "3.5",
            title = "Fundamentals of computer networks",
            topics = listOf(
                SpecTopic("3.5", "Fundamentals of computer networks"),
            ),
        ),
        SpecGroup(
            code = "3.6",
            title = "Cyber security",
            topics = listOf(
                SpecTopic("3.6.1", "Fundamentals of cyber security"),
                SpecTopic("3.6.2", "Cyber security threats"),
                SpecTopic("3.6.3", "Methods to detect and prevent cyber security threats"),
            ),
        ),
        SpecGroup(
            code = "3.7",
            title = "Relational databases and structured query language (SQL)",
            topics = listOf(
                SpecTopic("3.7.1", "Relational databases"),
                SpecTopic("3.7.2", "Structured query language (SQL)"),
            ),
        ),
        SpecGroup(
            code = "3.8",
            title = "Ethical, legal and environmental impacts of digital technology on wider society, including issues of privacy",
            topics = listOf(
                SpecTopic("3.8", "Ethical, legal and environmental impacts of digital technology on wider society, including issues of privacy"),
            ),
        ),
    ),
)
