// GENERATED by tools/spec_tool.py from the exam board's own specification.
// Do not edit by hand: run `python tools/spec_tool.py generate` instead.
// Source: https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/subject-content
// Checked: 2026-09-20

package revision.core.catalogue.aqa

import revision.core.catalogue.Board
import revision.core.catalogue.SpecGroup
import revision.core.catalogue.SpecSubject
import revision.core.catalogue.SpecTopic

val aqaEnglishLanguage: SpecSubject = SpecSubject(
    key = "english-language",
    ref = "aqa/english-language-8700",
    board = Board.AQA,
    name = "English Language",
    specCode = "8700",
    sourceUrl = "https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/subject-content",
    checkedOn = "2026-09-20",
    groups = listOf(
        SpecGroup(
            code = "3.1",
            title = "Scope of study",
            topics = listOf(
                SpecTopic("3.1.1", "Critical reading and comprehension"),
                SpecTopic("3.1.2", "Writing"),
                SpecTopic("3.1.3", "Spoken language"),
            ),
        ),
    ),
)
