// GENERATED by tools/spec_tool.py from the exam board's own specification.
// Do not edit by hand: run `python tools/spec_tool.py generate` instead.
// Source: https://www.aqa.org.uk/subjects/english/gcse/english-8702/specification/subject-content
// Checked: 2026-09-20

package revision.core.catalogue.aqa

import revision.core.catalogue.Board
import revision.core.catalogue.SpecGroup
import revision.core.catalogue.SpecSubject
import revision.core.catalogue.SpecTopic

val aqaEnglishLiterature: SpecSubject = SpecSubject(
    key = "english-literature",
    ref = "aqa/english-literature-8702",
    board = Board.AQA,
    name = "English Literature",
    specCode = "8702",
    sourceUrl = "https://www.aqa.org.uk/subjects/english/gcse/english-8702/specification/subject-content",
    checkedOn = "2026-09-20",
    groups = listOf(
        SpecGroup(
            code = "3.1.1",
            title = "Shakespeare",
            topics = listOf(
                SpecTopic(null, "Macbeth"),
                SpecTopic(null, "Romeo and Juliet"),
                SpecTopic(null, "The Tempest"),
                SpecTopic(null, "The Merchant of Venice"),
                SpecTopic(null, "Much Ado About Nothing"),
                SpecTopic(null, "Julius Caesar"),
            ),
        ),
        SpecGroup(
            code = "3.1.2",
            title = "The 19th-century novel",
            topics = listOf(
                SpecTopic(null, "The Strange Case of Dr Jekyll and Mr Hyde (Robert Louis Stevenson)"),
                SpecTopic(null, "A Christmas Carol (Charles Dickens)"),
                SpecTopic(null, "Great Expectations (1867) (Charles Dickens)"),
                SpecTopic(null, "Jane Eyre (Charlotte Brontë)"),
                SpecTopic(null, "Frankenstein (1831) (Mary Shelley)"),
                SpecTopic(null, "Pride and Prejudice (Jane Austen)"),
                SpecTopic(null, "The Sign of Four (Sir Arthur Conan Doyle)"),
            ),
        ),
        SpecGroup(
            code = "3.2.1",
            title = "Modern texts",
            topics = listOf(
                SpecTopic(null, "An Inspector Calls (JB Priestley)"),
                SpecTopic(null, "Blood Brothers (musical version) (Willy Russell)"),
                SpecTopic(null, "The History Boys (Last exam 2024) (Alan Bennett)"),
                SpecTopic(null, "DNA (Dennis Kelly)"),
                SpecTopic(null, "The Curious Incident of the Dog in the Night-Time (play script) (Last exam 2024) (Simon Stephens)"),
                SpecTopic(null, "A Taste of Honey (Shelagh Delaney)"),
                SpecTopic(null, "Princess & The Hustler (First teaching 2023, first exam 2025) (Chinonyerem Odimba)"),
                SpecTopic(null, "Leave Taking (First teaching 2023, first exam 2025) (Winsome Pinnock)"),
                SpecTopic(null, "Lord of the Flies (William Golding)"),
                SpecTopic(null, "Telling Tales (AQA Anthology)"),
                SpecTopic(null, "Animal Farm (George Orwell)"),
                SpecTopic(null, "Never Let Me Go (Last exam 2024) (Kazuo Ishiguro)"),
                SpecTopic(null, "Anita and Me (Meera Syal)"),
                SpecTopic(null, "Pigeon English (Stephen Kelman)"),
                SpecTopic(null, "My Name is Leon (First teaching 2023, first exam 2025) (Kit de Waal)"),
            ),
        ),
        SpecGroup(
            code = "3.2.2",
            title = "Poetry",
            topics = listOf(
                SpecTopic(null, "Love and Relationships"),
                SpecTopic(null, "Power and Conflict"),
                SpecTopic(null, "Worlds and Lives (First teaching 2023, first exam 2025)"),
            ),
        ),
        SpecGroup(
            code = "3.2.3",
            title = "Unseen poetry",
            topics = listOf(
                SpecTopic("3.2.3", "Unseen poetry"),
            ),
        ),
        SpecGroup(
            code = "3.3",
            title = "Skills",
            topics = listOf(
                SpecTopic("3.3", "Skills"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "Reading comprehension and reading critically",
            topics = listOf(
                SpecTopic(null, "literal and inferential comprehension: understanding a word, phrase or sentence in context; exploring aspects of plot, characterisation, events and settings; distinguishing between what is stated explicitly and what is implied; explaining motivation, sequence of events, and the relationship between actions or events"),
                SpecTopic(null, "critical reading: identifying the theme and distinguishing between themes; supporting a point of view by referring to evidence in the text; recognising the possibility of and evaluating different responses to a text; using understanding of writers’ social, historical and cultural contexts to inform evaluation; making an informed personal response that derives from analysis and evaluation of the text"),
                SpecTopic(null, "evaluation of a writer’s choice of vocabulary, grammatical and structural features: analysing and evaluating how language, structure, form and presentation contribute to quality and impact; using linguistic and literary terminology for such evaluation"),
                SpecTopic(null, "comparing texts: comparing and contrasting texts studied, referring where relevant to theme, characterisation, context (where known), style and literary quality; comparing two texts critically with respect to the above"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "Writing",
            topics = listOf(
                SpecTopic(null, "producing clear and coherent text: writing effectively about literature for a range of purposes such as: to describe, explain, summarise, argue, analyse and evaluate; discussing and maintaining a point of view; selecting and emphasising key points; using relevant quotation and using detailed textual references"),
                SpecTopic(null, "accurate Standard English: accurate spelling, punctuation and grammar"),
            ),
        ),
    ),
)
