// GENERATED by tools/spec_tool.py from the exam board's own specification.
// Do not edit by hand: run `python tools/spec_tool.py generate` instead.
// Source: https://www.aqa.org.uk/subjects/french/gcse/french-8652/specification/subject-content
// Checked: 2026-09-20

package revision.core.catalogue.aqa

import revision.core.catalogue.Board
import revision.core.catalogue.SpecGroup
import revision.core.catalogue.SpecSubject
import revision.core.catalogue.SpecTopic

val aqaFrench: SpecSubject = SpecSubject(
    key = "french",
    ref = "aqa/french-8652",
    board = Board.AQA,
    name = "French",
    specCode = "8652",
    sourceUrl = "https://www.aqa.org.uk/subjects/french/gcse/french-8652/specification/subject-content",
    checkedOn = "2026-09-20",
    groups = listOf(
        SpecGroup(
            code = "3.1.1",
            title = "Theme 1: People and lifestyle",
            topics = listOf(
                SpecTopic(null, "Topic 1: Identity and relationships with others"),
                SpecTopic(null, "Topic 2: Healthy living and lifestyle"),
                SpecTopic(null, "Topic 3: Education and work"),
            ),
        ),
        SpecGroup(
            code = "3.1.2",
            title = "Theme 2: Popular culture",
            topics = listOf(
                SpecTopic(null, "Topic 1: Free-time activities"),
                SpecTopic(null, "Topic 2: Customs, festivals and celebrations"),
                SpecTopic(null, "Topic 3: Celebrity culture"),
            ),
        ),
        SpecGroup(
            code = "3.1.3",
            title = "Theme 3: Communication and the world around us",
            topics = listOf(
                SpecTopic(null, "Topic 1: Travel and tourism, including places of interest"),
                SpecTopic(null, "Topic 2: Media and technology"),
                SpecTopic(null, "Topic 3: The environment and where people live"),
            ),
        ),
        SpecGroup(
            code = "3.2",
            title = "Grammar",
            topics = listOf(
                SpecTopic("3.2.1", "Foundation tier"),
                SpecTopic("3.2.2", "Higher tier"),
            ),
        ),
    ),
)
