// GENERATED by tools/spec_tool.py from the exam board's own specification.
// Do not edit by hand: run `python tools/spec_tool.py generate` instead.
// Source: https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content
// Checked: 2026-09-20

package revision.core.catalogue.aqa

import revision.core.catalogue.Board
import revision.core.catalogue.SpecGroup
import revision.core.catalogue.SpecSubject
import revision.core.catalogue.SpecTopic

val aqaGeography: SpecSubject = SpecSubject(
    key = "geography",
    ref = "aqa/geography-8035",
    board = Board.AQA,
    name = "Geography",
    specCode = "8035",
    sourceUrl = "https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content",
    checkedOn = "2026-09-20",
    groups = listOf(
        SpecGroup(
            code = "3.1.1",
            title = "Section A: The challenge of natural hazards",
            topics = listOf(
                SpecTopic("3.1.1.1", "Natural hazards"),
                SpecTopic("3.1.1.2", "Tectonic hazards"),
                SpecTopic("3.1.1.3", "Weather hazards"),
                SpecTopic("3.1.1.4", "Climate change"),
            ),
        ),
        SpecGroup(
            code = "3.1.2",
            title = "Section B: The living world",
            topics = listOf(
                SpecTopic("3.1.2.1", "Ecosystems"),
                SpecTopic("3.1.2.2", "Tropical rainforests"),
                SpecTopic("3.1.2.3", "Hot deserts"),
                SpecTopic("3.1.2.4", "Cold environments"),
            ),
        ),
        SpecGroup(
            code = "3.1.3",
            title = "Section C: Physical landscapes in the UK",
            topics = listOf(
                SpecTopic("3.1.3.1", "UK physical landscapes"),
                SpecTopic("3.1.3.2", "Coastal landscapes in the UK"),
                SpecTopic("3.1.3.3", "River landscapes in the UK"),
                SpecTopic("3.1.3.4", "Glacial landscapes in the UK"),
            ),
        ),
        SpecGroup(
            code = "3.2.1",
            title = "Section A: Urban issues and challenges",
            topics = listOf(
                SpecTopic("3.2.1", "Section A: Urban issues and challenges"),
            ),
        ),
        SpecGroup(
            code = "3.2.2",
            title = "Section B: The changing economic world",
            topics = listOf(
                SpecTopic("3.2.2", "Section B: The changing economic world"),
            ),
        ),
        SpecGroup(
            code = "3.2.3",
            title = "Section C: The challenge of resource management",
            topics = listOf(
                SpecTopic("3.2.3.1", "Resource management"),
                SpecTopic("3.2.3.2", "Food"),
                SpecTopic("3.2.3.3", "Water"),
                SpecTopic("3.2.3.4", "Energy"),
            ),
        ),
        SpecGroup(
            code = "3.3.1",
            title = "Section A: Issue evaluation",
            topics = listOf(
                SpecTopic("3.3.1", "Section A: Issue evaluation"),
            ),
        ),
        SpecGroup(
            code = "3.3.2",
            title = "Section B: Fieldwork",
            topics = listOf(
                SpecTopic("3.3.2", "Section B: Fieldwork"),
            ),
        ),
        SpecGroup(
            code = "3.4.1",
            title = "Cartographic skills",
            topics = listOf(
                SpecTopic("3.4.1", "Cartographic skills"),
            ),
        ),
        SpecGroup(
            code = "3.4.2",
            title = "Graphical skills",
            topics = listOf(
                SpecTopic("3.4.2", "Graphical skills"),
            ),
        ),
        SpecGroup(
            code = "3.4.3",
            title = "Numerical skills",
            topics = listOf(
                SpecTopic("3.4.3", "Numerical skills"),
            ),
        ),
        SpecGroup(
            code = "3.4.4",
            title = "Statistical skills",
            topics = listOf(
                SpecTopic("3.4.4", "Statistical skills"),
            ),
        ),
        SpecGroup(
            code = "3.4.5",
            title = "Use of qualitative and quantitative data",
            topics = listOf(
                SpecTopic("3.4.5", "Use of qualitative and quantitative data"),
            ),
        ),
        SpecGroup(
            code = "3.4.6",
            title = "Formulate enquiry and argument",
            topics = listOf(
                SpecTopic("3.4.6", "Formulate enquiry and argument"),
            ),
        ),
        SpecGroup(
            code = "3.4.7",
            title = "Literacy",
            topics = listOf(
                SpecTopic("3.4.7", "Literacy"),
            ),
        ),
    ),
)
