// GENERATED by tools/spec_tool.py from the exam board's own specification.
// Do not edit by hand: run `python tools/spec_tool.py generate` instead.
// Source: https://www.aqa.org.uk/subjects/history/gcse/history-8145/specification/subject-content
// Checked: 2026-09-20

package revision.core.catalogue.aqa

import revision.core.catalogue.Board
import revision.core.catalogue.Choice
import revision.core.catalogue.SpecGroup
import revision.core.catalogue.SpecSubject
import revision.core.catalogue.SpecTopic

val aqaHistory: SpecSubject = SpecSubject(
    key = "history",
    ref = "aqa/history-8145",
    board = Board.AQA,
    name = "History",
    specCode = "8145",
    sourceUrl = "https://www.aqa.org.uk/subjects/history/gcse/history-8145/specification/subject-content",
    checkedOn = "2026-09-20",
    groups = listOf(
        SpecGroup(
            code = "3.1",
            title = "Rationale",
            topics = listOf(
                SpecTopic("3.1", "Rationale"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "AA America, 1840–1895: Expansion and consolidation",
            topics = listOf(
                SpecTopic(null, "Part one: Expansion: opportunities and challenges"),
                SpecTopic(null, "Part two: Conflict across America"),
                SpecTopic(null, "Part three: Consolidation: forging the nation"),
            ),
            choice = Choice("Section A: Period studies", 1),
        ),
        SpecGroup(
            code = null,
            title = "AB Germany, 1890–1945: Democracy and dictatorship",
            topics = listOf(
                SpecTopic(null, "Part one: Germany and the growth of democracy"),
                SpecTopic(null, "Part two: Germany and the Depression"),
                SpecTopic(null, "Part three: The experiences of Germans under the Nazis"),
            ),
            choice = Choice("Section A: Period studies", 1),
        ),
        SpecGroup(
            code = null,
            title = "AC Russia, 1894–1945: Tsardom and communism",
            topics = listOf(
                SpecTopic(null, "Part one: The end of Tsardom"),
                SpecTopic(null, "Part two: Lenin's new society"),
                SpecTopic(null, "Part three: Stalin's USSR"),
            ),
            choice = Choice("Section A: Period studies", 1),
        ),
        SpecGroup(
            code = null,
            title = "AD America, 1920–1973: Opportunity and inequality",
            topics = listOf(
                SpecTopic(null, "Part one: American people and the 'Boom'"),
                SpecTopic(null, "Part two: Bust – Americans' experiences of the Depression and New Deal"),
                SpecTopic(null, "Part three: Post-war America"),
            ),
            choice = Choice("Section A: Period studies", 1),
        ),
        SpecGroup(
            code = null,
            title = "BA Conflict and tension: the First World War, 1894–1918",
            topics = listOf(
                SpecTopic(null, "Part one: The causes of the First World War"),
                SpecTopic(null, "Part two: The First World War: stalemate"),
                SpecTopic(null, "Part three: Ending the war"),
            ),
            choice = Choice("Section B: Wider world depth studies", 1),
        ),
        SpecGroup(
            code = null,
            title = "BB Conflict and tension: the inter-war years, 1918–1939",
            topics = listOf(
                SpecTopic(null, "Part one: Peacemaking"),
                SpecTopic(null, "Part two: The League of Nations and international peace"),
                SpecTopic(null, "Part three: The origins and outbreak of the Second World War"),
            ),
            choice = Choice("Section B: Wider world depth studies", 1),
        ),
        SpecGroup(
            code = null,
            title = "BC Conflict and tension between East and West, 1945–1972",
            topics = listOf(
                SpecTopic(null, "Part one: The origins of the Cold War"),
                SpecTopic(null, "Part two: The development of the Cold War"),
                SpecTopic(null, "Part three: Transformation of the Cold War"),
            ),
            choice = Choice("Section B: Wider world depth studies", 1),
        ),
        SpecGroup(
            code = null,
            title = "BD Conflict and tension in Asia, 1950–1975",
            topics = listOf(
                SpecTopic(null, "Part one: Conflict in Korea"),
                SpecTopic(null, "Part two: Escalation of conflict in Vietnam"),
                SpecTopic(null, "Part three: The ending of conflict in Vietnam"),
            ),
            choice = Choice("Section B: Wider world depth studies", 1),
        ),
        SpecGroup(
            code = null,
            title = "BE Conflict and tension in the Gulf and Afghanistan, 1990–2009",
            topics = listOf(
                SpecTopic(null, "Part one: Tensions in the Gulf"),
                SpecTopic(null, "Part two: The war on Al-Qaeda"),
                SpecTopic(null, "Part three: The Iraq War"),
            ),
            choice = Choice("Section B: Wider world depth studies", 1),
        ),
        SpecGroup(
            code = null,
            title = "AA Britain: Health and the people: c1000 to the present day",
            topics = listOf(
                SpecTopic(null, "Part one: Medicine stands still"),
                SpecTopic(null, "Part two: The beginnings of change"),
                SpecTopic(null, "Part three: A revolution in medicine"),
                SpecTopic(null, "Part four: Modern medicine"),
            ),
            choice = Choice("Section A: Thematic studies", 1),
        ),
        SpecGroup(
            code = null,
            title = "BB Britain: Power and the people: c1170 to the present day",
            topics = listOf(
                SpecTopic(null, "Part one: Challenging authority and feudalism"),
                SpecTopic(null, "Part two: Challenging royal authority"),
                SpecTopic(null, "Part three: Reform and reformers"),
                SpecTopic(null, "Part four: Equality and rights"),
            ),
            choice = Choice("Section A: Thematic studies", 1),
        ),
        SpecGroup(
            code = null,
            title = "AC Britain: Migration, empires and the people: c790 to the present day",
            topics = listOf(
                SpecTopic(null, "Part one: Conquered and conquerors"),
                SpecTopic(null, "Part two: Looking west"),
                SpecTopic(null, "Part three: Expansion and empire"),
                SpecTopic(null, "Part four: Britain in the 20th century"),
            ),
            choice = Choice("Section A: Thematic studies", 1),
        ),
        SpecGroup(
            code = null,
            title = "BA Norman England, c1066–c1100",
            topics = listOf(
                SpecTopic(null, "Part one: The Normans: conquest and control"),
                SpecTopic(null, "Part two: Life under the Normans"),
                SpecTopic(null, "Part three: The Norman Church and monasticism"),
                SpecTopic(null, "Part four: The historic environment of Norman England"),
            ),
            choice = Choice("Section B: British depth studies", 1),
        ),
        SpecGroup(
            code = null,
            title = "BB Medieval England - the reign of Edward I, 1272–1307",
            topics = listOf(
                SpecTopic(null, "Part one: Government, the rights of King and people"),
                SpecTopic(null, "Part two: Life in Medieval England"),
                SpecTopic(null, "Part three: Edward I’s military campaigns in Wales and Scotland"),
                SpecTopic(null, "Part four: The historic environment of Medieval England"),
            ),
            choice = Choice("Section B: British depth studies", 1),
        ),
        SpecGroup(
            code = null,
            title = "BC Elizabethan England, c1568–1603",
            topics = listOf(
                SpecTopic(null, "Part one: Elizabeth's court and Parliament"),
                SpecTopic(null, "Part two: Life in Elizabethan times"),
                SpecTopic(null, "Part three: Troubles at home and abroad"),
                SpecTopic(null, "Part four: The historic environment of Elizabethan England"),
            ),
            choice = Choice("Section B: British depth studies", 1),
        ),
        SpecGroup(
            code = null,
            title = "BD Restoration England, 1660–1685",
            topics = listOf(
                SpecTopic(null, "Part one: Crown, Parliament, plots and court life"),
                SpecTopic(null, "Part two: Life in Restoration England"),
                SpecTopic(null, "Part three: Land, trade and war"),
                SpecTopic(null, "Part four: The historic environment of Restoration England"),
            ),
            choice = Choice("Section B: British depth studies", 1),
        ),
    ),
)
