// GENERATED by tools/spec_tool.py from the exam board's own specification.
// Do not edit by hand: run `python tools/spec_tool.py generate` instead.
// Source: https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content
// Checked: 2026-09-20

package revision.core.catalogue.aqa

import revision.core.catalogue.Board
import revision.core.catalogue.SpecGroup
import revision.core.catalogue.SpecSubject
import revision.core.catalogue.SpecTopic
import revision.core.catalogue.Tier

val aqaMaths: SpecSubject = SpecSubject(
    key = "maths",
    ref = "aqa/maths-8300",
    board = Board.AQA,
    name = "Maths",
    specCode = "8300",
    sourceUrl = "https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content",
    checkedOn = "2026-09-20",
    groups = listOf(
        SpecGroup(
            code = "3.1.1",
            title = "Structure and calculation",
            topics = listOf(
                SpecTopic("N1", "order positive and negative integers, decimals and fractions use the symbols =, ≠, <, >, ≤, ≥"),
                SpecTopic("N2", "apply the four operations, including formal written methods, to integers, decimals and simple fractions (proper and i…"),
                SpecTopic("N3", "recognise and use relationships between operations, including inverse operations (eg cancellation to simplify calcula…"),
                SpecTopic("N4", "use the concepts and vocabulary of prime numbers, factors (divisors), multiples, common factors, common multiples, hi…"),
                SpecTopic("N5", "apply systematic listing strategies"),
                SpecTopic("N6", "use positive integer powers and associated real roots (square, cube and higher), recognise powers of 2, 3, 4, 5"),
                SpecTopic("N7", "calculate with roots, and with integer indices"),
                SpecTopic("N8", "calculate exactly with fractions"),
                SpecTopic("N9", "calculate with and interpret standard form A × 10 n , where 1 ≤ A 10 and n is an integer"),
            ),
        ),
        SpecGroup(
            code = "3.1.2",
            title = "Fractions, decimals and percentages",
            topics = listOf(
                SpecTopic("N10", "work interchangeably with terminating decimals and their corresponding fractions (such as 3.5 and 7 2 or 0.375 and 3 …"),
                SpecTopic("N11", "identify and work with fractions in ratio problems"),
                SpecTopic("N12", "interpret fractions and percentages as operators"),
            ),
        ),
        SpecGroup(
            code = "3.1.3",
            title = "Measures and accuracy",
            topics = listOf(
                SpecTopic("N13", "use standard units of mass, length, time, money and other measures (including standard compound measures) using decim…"),
                SpecTopic("N14", "estimate answers check calculations using approximation and estimation, including answers obtained using technology"),
                SpecTopic("N15", "round numbers and measures to an appropriate degree of accuracy (eg to a specified number of decimal places or signif…"),
                SpecTopic("N16", "apply and interpret limits of accuracy"),
            ),
        ),
        SpecGroup(
            code = "3.2.1",
            title = "Notation, vocabulary and manipulation",
            topics = listOf(
                SpecTopic("A1", "use and interpret algebraic notation, including: a b in place of a × b 3 y in place of y + y + y and 3 × y a 2 in pla…"),
                SpecTopic("A2", "substitute numerical values into formulae and expressions, including scientific formulae"),
                SpecTopic("A3", "understand and use the concepts and vocabulary of expressions, equations, formulae, inequalities, terms and factors"),
                SpecTopic("A4", "simplify and manipulate algebraic expressions by:"),
                SpecTopic("A5", "understand and use standard mathematical formulae rearrange formulae to change the subject"),
                SpecTopic("A6", "know the difference between an equation and an identity"),
                SpecTopic("A7", "where appropriate, interpret simple expressions as functions with inputs and outputs"),
            ),
        ),
        SpecGroup(
            code = "3.2.2",
            title = "Graphs",
            topics = listOf(
                SpecTopic("A8", "work with coordinates in all four quadrants"),
                SpecTopic("A9", "plot graphs of equations that correspond to straight-line graphs in the coordinate plane"),
                SpecTopic("A10", "identify and interpret gradients and intercepts of linear functions graphically and algebraically"),
                SpecTopic("A11", "identify and interpret roots, intercepts and turning points of quadratic functions graphically"),
                SpecTopic("A12", "recognise, sketch and interpret graphs of linear functions and quadratic functions"),
                SpecTopic("A13", "sketch translations and reflections of a given function", Tier.HIGHER),
                SpecTopic("A14", "plot and interpret graphs, and graphs of non-standard functions in real contexts, to find approximate solutions to pr…"),
                SpecTopic("A15", "calculate or estimate gradients of graphs and areas under graphs (including quadratic and other non-linear graphs), a…", Tier.HIGHER),
                SpecTopic("A16", "recognise and use the equation of a circle with centre at the origin find the equation of a tangent to a circle at a …", Tier.HIGHER),
            ),
        ),
        SpecGroup(
            code = "3.2.3",
            title = "Solving equations and inequalities",
            topics = listOf(
                SpecTopic("A17", "solve linear equations in one unknown algebraically find approximate solutions using a graph"),
                SpecTopic("A18", "solve quadratic equations algebraically by factorising"),
                SpecTopic("A19", "solve two simultaneous equations in two variables (linear/linear) algebraically find approximate solutions using a gr…"),
                SpecTopic("A20", "find approximate solutions to equations numerically using iteration", Tier.HIGHER),
                SpecTopic("A21", "translate simple situations or procedures into algebraic expressions or formulae derive an equation (or two simultane…"),
                SpecTopic("A22", "solve linear inequalities in one variable"),
            ),
        ),
        SpecGroup(
            code = "3.2.4",
            title = "Sequences",
            topics = listOf(
                SpecTopic("A23", "generate terms of a sequence from either a term-to-term or a position-to-term rule"),
                SpecTopic("A24", "recognise and use sequences of triangular, square and cube numbers and simple arithmetic progressions"),
                SpecTopic("A25", "deduce expressions to calculate the n th term of linear sequences"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "R1",
            topics = listOf(
                SpecTopic(null, "R1"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "R2",
            topics = listOf(
                SpecTopic(null, "R2"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "R3",
            topics = listOf(
                SpecTopic(null, "R3"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "R4",
            topics = listOf(
                SpecTopic(null, "R4"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "R5",
            topics = listOf(
                SpecTopic(null, "R5"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "R6",
            topics = listOf(
                SpecTopic(null, "R6"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "R7",
            topics = listOf(
                SpecTopic(null, "R7"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "R8",
            topics = listOf(
                SpecTopic(null, "R8"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "R9",
            topics = listOf(
                SpecTopic(null, "R9"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "R10",
            topics = listOf(
                SpecTopic(null, "R10"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "R11",
            topics = listOf(
                SpecTopic(null, "R11"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "R12",
            topics = listOf(
                SpecTopic(null, "R12"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "R13",
            topics = listOf(
                SpecTopic(null, "R13"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "R14",
            topics = listOf(
                SpecTopic(null, "R14"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "R15",
            topics = listOf(
                SpecTopic(null, "R15"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "R16",
            topics = listOf(
                SpecTopic(null, "R16"),
            ),
        ),
        SpecGroup(
            code = "3.4.1",
            title = "Properties and constructions",
            topics = listOf(
                SpecTopic("G1", "use conventional terms and notations: points, lines, vertices, edges, planes, parallel lines, perpendicular lines, ri…"),
                SpecTopic("G2", "use the standard ruler and compass constructions (perpendicular bisector of a line segment, constructing a perpendicu…"),
                SpecTopic("G3", "apply the properties of angles at a point, angles at a point on a straight line, vertically opposite angles understan…"),
                SpecTopic("G4", "derive and apply the properties and definitions of: special types of quadrilaterals, including square, rectangle, par…"),
                SpecTopic("G5", "use the basic congruence criteria for triangles (SSS, SAS, ASA, RHS)"),
                SpecTopic("G6", "apply angle facts, triangle congruence, similarity and properties of quadrilaterals to conjecture and derive results …"),
                SpecTopic("G7", "identify, describe and construct congruent and similar shapes, including on coordinate axes, by considering rotation,…"),
                SpecTopic("G8", "describe the changes and invariance achieved by combinations of rotations, reflections and translations", Tier.HIGHER),
                SpecTopic("G9", "identify and apply circle definitions and properties, including: centre, radius, chord, diameter, circumference"),
                SpecTopic("G10", "apply and prove the standard circle theorems concerning angles, radii, tangents and chords, and use them to prove rel…", Tier.HIGHER),
                SpecTopic("G11", "solve geometrical problems on coordinate axes"),
                SpecTopic("G12", "identify properties of the faces, surfaces, edges and vertices of: cubes, cuboids, prisms, cylinders, pyramids, cones…"),
                SpecTopic("G13", "interpret plans and elevations of 3D shapes"),
            ),
        ),
        SpecGroup(
            code = "3.4.2",
            title = "Mensuration and calculation",
            topics = listOf(
                SpecTopic("G14", "use standard units of measure and related concepts (length, area, volume/capacity, mass, time, money etc.)"),
                SpecTopic("G15", "measure line segments and angles in geometric figures, including interpreting maps and scale drawings and use of bear…"),
                SpecTopic("G16", "know and apply formulae to calculate: area of triangles, parallelograms, trapezia; volume of cuboids and other right …"),
                SpecTopic("G17", "know the formulae: circumference of a circle = 2 π r = π d area of a circle = π r 2 calculate perimeters of 2D shapes…"),
                SpecTopic("G18", "calculate arc lengths, angles and areas of sectors of circles"),
                SpecTopic("G19", "apply the concepts of congruence and similarity, including the relationships between lengths in similar figures"),
                SpecTopic("G20", "know the formulae for: Pythagoras’ theorem, a 2 + b 2 = c 2 and the trigonometric ratios, sin θ = opposite hypotenuse…"),
                SpecTopic("G21", "know the exact values of sin θ and cos θ for θ = 0°, 30°, 45° , 60° and 90° know the exact value of tan θ for θ = 0°,…"),
                SpecTopic("G22", "know and apply the sine rule, a sin ⁡ A = b sin ⁡ B = c sin ⁡ C and cosine rule, a 2 = b 2 + c 2 - 2 b c cos A to fin…", Tier.HIGHER),
                SpecTopic("G23", "know and apply A r e a = 1 2 a b sin C to calculate the area, sides or angles of any triangle", Tier.HIGHER),
            ),
        ),
        SpecGroup(
            code = "3.4.3",
            title = "Vectors",
            topics = listOf(
                SpecTopic("G24", "describe translations as 2D vectors"),
                SpecTopic("G25", "apply addition and subtraction of vectors, multiplication of vectors by a scalar, and diagrammatic and column represe…"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "P1",
            topics = listOf(
                SpecTopic(null, "P1"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "P2",
            topics = listOf(
                SpecTopic(null, "P2"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "P3",
            topics = listOf(
                SpecTopic(null, "P3"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "P4",
            topics = listOf(
                SpecTopic(null, "P4"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "P5",
            topics = listOf(
                SpecTopic(null, "P5"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "P6",
            topics = listOf(
                SpecTopic(null, "P6"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "P7",
            topics = listOf(
                SpecTopic(null, "P7"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "P8",
            topics = listOf(
                SpecTopic(null, "P8"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "P9",
            topics = listOf(
                SpecTopic(null, "P9"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "S1",
            topics = listOf(
                SpecTopic(null, "S1"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "S2",
            topics = listOf(
                SpecTopic(null, "S2"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "S3",
            topics = listOf(
                SpecTopic(null, "S3"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "S4",
            topics = listOf(
                SpecTopic(null, "S4"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "S5",
            topics = listOf(
                SpecTopic(null, "S5"),
            ),
        ),
        SpecGroup(
            code = null,
            title = "S6",
            topics = listOf(
                SpecTopic(null, "S6"),
            ),
        ),
    ),
)
