// GENERATED by tools/spec_tool.py from the exam board's own specification.
// Do not edit by hand: run `python tools/spec_tool.py generate` instead.
// Source: https://www.aqa.org.uk/subjects/physics/gcse/physics-8463/specification/subject-content
// Checked: 2026-09-20

package revision.core.catalogue.aqa

import revision.core.catalogue.Board
import revision.core.catalogue.SpecGroup
import revision.core.catalogue.SpecSubject
import revision.core.catalogue.SpecTopic

val aqaPhysics: SpecSubject = SpecSubject(
    key = "physics",
    ref = "aqa/physics-8463",
    board = Board.AQA,
    name = "Physics",
    specCode = "8463",
    sourceUrl = "https://www.aqa.org.uk/subjects/physics/gcse/physics-8463/specification/subject-content",
    checkedOn = "2026-09-20",
    groups = listOf(
        SpecGroup(
            code = "4.1",
            title = "Energy",
            topics = listOf(
                SpecTopic("4.1.1", "Energy changes in a system, and the ways energy is stored before and after such changes"),
                SpecTopic("4.1.2", "Conservation and dissipation of energy"),
                SpecTopic("4.1.3", "National and global energy resources"),
            ),
        ),
        SpecGroup(
            code = "4.2",
            title = "Electricity",
            topics = listOf(
                SpecTopic("4.2.1", "Current, potential difference and resistance"),
                SpecTopic("4.2.2", "Series and parallel circuits"),
                SpecTopic("4.2.3", "Domestic uses and safety"),
                SpecTopic("4.2.4", "Energy transfers"),
                SpecTopic("4.2.5", "Static electricity (physics only)"),
            ),
        ),
        SpecGroup(
            code = "4.3",
            title = "Particle model of matter",
            topics = listOf(
                SpecTopic("4.3.1", "Changes of state and the particle model"),
                SpecTopic("4.3.2", "Internal energy and energy transfers"),
                SpecTopic("4.3.3", "Particle model and pressure"),
            ),
        ),
        SpecGroup(
            code = "4.4",
            title = "Atomic structure",
            topics = listOf(
                SpecTopic("4.4.1", "Atoms and isotopes"),
                SpecTopic("4.4.2", "Atoms and nuclear radiation"),
                SpecTopic("4.4.3", "Hazards and uses of radioactive emissions and of background radiation (physics only)"),
                SpecTopic("4.4.4", "Nuclear fission and fusion (physics only)"),
            ),
        ),
        SpecGroup(
            code = "4.5",
            title = "Forces",
            topics = listOf(
                SpecTopic("4.5.1", "Forces and their interactions"),
                SpecTopic("4.5.2", "Work done and energy transfer"),
                SpecTopic("4.5.3", "Forces and elasticity"),
                SpecTopic("4.5.4", "Moments, levers and gears (physics only)"),
                SpecTopic("4.5.5", "Pressure and pressure differences in fluids (physics only)"),
                SpecTopic("4.5.6", "Forces and motion"),
                SpecTopic("4.5.7", "Momentum (HT only)"),
            ),
        ),
        SpecGroup(
            code = "4.6",
            title = "Waves",
            topics = listOf(
                SpecTopic("4.6.1", "Waves in air, fluids and solids"),
                SpecTopic("4.6.2", "Electromagnetic waves"),
                SpecTopic("4.6.3", "Black body radiation (physics only)"),
            ),
        ),
        SpecGroup(
            code = "4.7",
            title = "Magnetism and electromagnetism",
            topics = listOf(
                SpecTopic("4.7.1", "Permanent and induced magnetism, magnetic forces and fields"),
                SpecTopic("4.7.2", "The motor effect"),
                SpecTopic("4.7.3", "Induced potential, transformers and the National Grid (physics only) (HT only)"),
            ),
        ),
        SpecGroup(
            code = "4.8",
            title = "Space physics (physics only)",
            topics = listOf(
                SpecTopic("4.8.1", "Solar system; stability of orbital motions; satellites (physics only)"),
                SpecTopic("4.8.2", "Red-shift (physics only)"),
            ),
        ),
        SpecGroup(
            code = "4.9",
            title = "Key ideas",
            topics = listOf(
                SpecTopic("4.9", "Key ideas"),
            ),
        ),
    ),
)
