// GENERATED by tools/spec_tool.py from the exam board's own specification.
// Do not edit by hand: run `python tools/spec_tool.py generate` instead.
// Source: https://www.aqa.org.uk/subjects/religious-studies/gcse/religious-studies-8062/specification/subject-content
// Checked: 2026-09-20

package revision.core.catalogue.aqa

import revision.core.catalogue.Board
import revision.core.catalogue.SpecGroup
import revision.core.catalogue.SpecSubject
import revision.core.catalogue.SpecTopic

val aqaReligiousStudies: SpecSubject = SpecSubject(
    key = "religious-studies",
    ref = "aqa/religious-studies-8062",
    board = Board.AQA,
    name = "Religious Studies",
    specCode = "8062",
    sourceUrl = "https://www.aqa.org.uk/subjects/religious-studies/gcse/religious-studies-8062/specification/subject-content",
    checkedOn = "2026-09-20",
    groups = listOf(
        SpecGroup(
            code = "3.1",
            title = "Component 1: The study of religions: beliefs, teachings and practices",
            topics = listOf(
                SpecTopic("3.1.1", "Buddhism"),
                SpecTopic("3.1.2", "Christianity"),
                SpecTopic("3.1.3", "Catholic Christianity"),
                SpecTopic("3.1.4", "Hinduism"),
                SpecTopic("3.1.5", "Islam"),
                SpecTopic("3.1.6", "Judaism"),
                SpecTopic("3.1.7", "Sikhism"),
            ),
        ),
        SpecGroup(
            code = "3.2",
            title = "Component 2: Thematic studies",
            topics = listOf(
                SpecTopic("3.2.1", "Religious, philosophical and ethical studies"),
                SpecTopic("3.2.2", "Textual studies"),
            ),
        ),
    ),
)
