// GENERATED by tools/spec_tool.py from the exam board's own specification.
// Do not edit by hand: run `python tools/spec_tool.py generate` instead.
// Source: https://www.ocr.org.uk/images/234594-specification-accredited-gcse-gateway-science-suite-biology-a-j247.pdf
// Checked: 2026-09-20

package revision.core.catalogue.ocr

import revision.core.catalogue.Board
import revision.core.catalogue.SpecGroup
import revision.core.catalogue.SpecSubject
import revision.core.catalogue.SpecTopic

val ocrBiology: SpecSubject = SpecSubject(
    key = "biology",
    ref = "ocr/biology-j247",
    board = Board.OCR,
    name = "Biology",
    specCode = "J247",
    sourceUrl = "https://www.ocr.org.uk/images/234594-specification-accredited-gcse-gateway-science-suite-biology-a-j247.pdf",
    checkedOn = "2026-09-20",
    groups = listOf(
        SpecGroup(
            code = "B1",
            title = "Cell level systems",
            topics = listOf(
                SpecTopic("B1.1", "Cell structures"),
                SpecTopic("B1.2", "What happens in cells (and what do cells need)?"),
                SpecTopic("B1.3", "Respiration"),
                SpecTopic("B1.4", "Photosynthesis"),
            ),
        ),
        SpecGroup(
            code = "B2",
            title = "Scaling up",
            topics = listOf(
                SpecTopic("B2.1", "Supplying the cell"),
                SpecTopic("B2.2", "The challenges of size"),
            ),
        ),
        SpecGroup(
            code = "B3",
            title = "Organism level systems",
            topics = listOf(
                SpecTopic("B3.1", "Coordination and control – the nervous system"),
                SpecTopic("B3.2", "Coordination and control – the endocrine system"),
                SpecTopic("B3.3", "Maintaining internal environments"),
            ),
        ),
        SpecGroup(
            code = "B4",
            title = "Community level systems",
            topics = listOf(
                SpecTopic("B4.1", "Ecosystems"),
            ),
        ),
        SpecGroup(
            code = "B5",
            title = "Genes, inheritance and selection",
            topics = listOf(
                SpecTopic("B5.1", "Inheritance"),
                SpecTopic("B5.2", "Natural selection and evolution"),
            ),
        ),
        SpecGroup(
            code = "B6",
            title = "Global challenges",
            topics = listOf(
                SpecTopic("B6.1", "Monitoring and maintaining the environment"),
                SpecTopic("B6.2", "Feeding the human race"),
                SpecTopic("B6.3", "Monitoring and maintaining health"),
            ),
        ),
    ),
)
