// GENERATED by tools/spec_tool.py from the exam board's own specification.
// Do not edit by hand: run `python tools/spec_tool.py generate` instead.
// Source: https://www.ocr.org.uk/images/234598-specification-accredited-gcse-gateway-science-suite-chemistry-a-j248.pdf
// Checked: 2026-09-20

package revision.core.catalogue.ocr

import revision.core.catalogue.Board
import revision.core.catalogue.SpecGroup
import revision.core.catalogue.SpecSubject
import revision.core.catalogue.SpecTopic

val ocrChemistry: SpecSubject = SpecSubject(
    key = "chemistry",
    ref = "ocr/chemistry-j248",
    board = Board.OCR,
    name = "Chemistry",
    specCode = "J248",
    sourceUrl = "https://www.ocr.org.uk/images/234598-specification-accredited-gcse-gateway-science-suite-chemistry-a-j248.pdf",
    checkedOn = "2026-09-20",
    groups = listOf(
        SpecGroup(
            code = "C1",
            title = "Particles",
            topics = listOf(
                SpecTopic("C1.1", "The particle model"),
                SpecTopic("C1.2", "Atomic structure"),
            ),
        ),
        SpecGroup(
            code = "C2",
            title = "Elements, compounds and mixtures",
            topics = listOf(
                SpecTopic("C2.1", "Purity and separating mixtures"),
                SpecTopic("C2.2", "Bonding"),
                SpecTopic("C2.3", "Properties of materials"),
            ),
        ),
        SpecGroup(
            code = "C3",
            title = "Chemical reactions",
            topics = listOf(
                SpecTopic("C3.1", "Introducing chemical reactions"),
                SpecTopic("C3.2", "Energetics"),
                SpecTopic("C3.3", "Types of chemical reactions"),
                SpecTopic("C3.4", "Electrolysis"),
            ),
        ),
        SpecGroup(
            code = "C4",
            title = "Predicting and identifying reactions and products",
            topics = listOf(
                SpecTopic("C4.1", "Predicting chemical reactions"),
                SpecTopic("C4.2", "Identifying the products of chemical reactions"),
            ),
        ),
        SpecGroup(
            code = "C5",
            title = "Monitoring and controlling chemical",
            topics = listOf(
                SpecTopic("C5.1", "Monitoring chemical reactions"),
                SpecTopic("C5.2", "Controlling reactions"),
                SpecTopic("C5.3", "Equilibria"),
            ),
        ),
        SpecGroup(
            code = "C6",
            title = "Global challenges",
            topics = listOf(
                SpecTopic("C6.1", "Improving processes and products"),
                SpecTopic("C6.2", "Organic chemistry"),
                SpecTopic("C6.3", "Interpreting and interacting with earth systems"),
            ),
        ),
    ),
)
