// GENERATED by tools/spec_tool.py from the exam board's own specification.
// Do not edit by hand: run `python tools/spec_tool.py generate` instead.
// Source: https://www.ocr.org.uk/Images/558027-specification-gcse-computer-science-j277.pdf
// Checked: 2026-09-20

package revision.core.catalogue.ocr

import revision.core.catalogue.Board
import revision.core.catalogue.SpecGroup
import revision.core.catalogue.SpecSubject
import revision.core.catalogue.SpecTopic

val ocrComputerScience: SpecSubject = SpecSubject(
    key = "computer-science",
    ref = "ocr/computer-science-j277",
    board = Board.OCR,
    name = "Computer Science",
    specCode = "J277",
    sourceUrl = "https://www.ocr.org.uk/Images/558027-specification-gcse-computer-science-j277.pdf",
    checkedOn = "2026-09-20",
    groups = listOf(
        SpecGroup(
            code = "1.1",
            title = "Systems architecture",
            topics = listOf(
                SpecTopic("1.1.1", "Architecture of the CPU"),
                SpecTopic("1.1.2", "CPU performance"),
                SpecTopic("1.1.3", "Embedded systems"),
            ),
        ),
        SpecGroup(
            code = "1.2",
            title = "Memory and storage",
            topics = listOf(
                SpecTopic("1.2.1", "Primary storage (memory)"),
                SpecTopic("1.2.2", "Secondary storage"),
                SpecTopic("1.2.3", "Units"),
                SpecTopic("1.2.4", "Data storage"),
                SpecTopic("1.2.5", "Compression"),
            ),
        ),
        SpecGroup(
            code = "1.3",
            title = "Computer networks, connections and protocols",
            topics = listOf(
                SpecTopic("1.3.1", "Networks and topologies"),
                SpecTopic("1.3.2", "Wired and wireless networks, protocols and layers"),
            ),
        ),
        SpecGroup(
            code = "1.4",
            title = "Network security",
            topics = listOf(
                SpecTopic("1.4.1", "Threats to computer systems and networks"),
                SpecTopic("1.4.2", "Identifying and preventing vulnerabilities"),
            ),
        ),
        SpecGroup(
            code = "1.5",
            title = "Systems software",
            topics = listOf(
                SpecTopic("1.5.1", "Operating systems"),
                SpecTopic("1.5.2", "Utility software"),
            ),
        ),
        SpecGroup(
            code = "1.6",
            title = "Ethical, legal, cultural and environmental impacts of digital technology",
            topics = listOf(
                SpecTopic("1.6.1", "Ethical, legal, cultural and environmental impact"),
            ),
        ),
        SpecGroup(
            code = "2.1",
            title = "Algorithms",
            topics = listOf(
                SpecTopic("2.1.1", "Computational thinking"),
                SpecTopic("2.1.2", "Designing, creating and refining algorithms"),
                SpecTopic("2.1.3", "Searching and sorting algorithms"),
            ),
        ),
        SpecGroup(
            code = "2.2",
            title = "Programming fundamentals",
            topics = listOf(
                SpecTopic("2.2.1", "Programming fundamentals"),
                SpecTopic("2.2.2", "Data types"),
                SpecTopic("2.2.3", "Additional programming techniques"),
            ),
        ),
        SpecGroup(
            code = "2.3",
            title = "Producing robust programs",
            topics = listOf(
                SpecTopic("2.3.1", "Defensive design"),
                SpecTopic("2.3.2", "Testing"),
            ),
        ),
        SpecGroup(
            code = "2.4",
            title = "Boolean logic",
            topics = listOf(
                SpecTopic("2.4.1", "Boolean logic"),
            ),
        ),
        SpecGroup(
            code = "2.5",
            title = "Programming languages and Integrated Development Environments",
            topics = listOf(
                SpecTopic("2.5.1", "Languages"),
                SpecTopic("2.5.2", "The Integrated Development Environment (IDE)"),
                SpecTopic("1.5.2", "Clarified the utility"),
                SpecTopic("2.1.2", "Added a new P ‘Use of"),
                SpecTopic("2.1.3", "Updated the first Pon"),
                SpecTopic("1.2.1", "Replaced ‘HDD’ with"),
                SpecTopic("1.2.4", "Under the guidance"),
                SpecTopic("1.3.2", "Updated the fifth P in"),
                SpecTopic("1.5.1", "Updated the third P in"),
            ),
        ),
    ),
)
