// GENERATED by tools/spec_tool.py — every subject in the catalogue.
// Do not edit by hand: run `python tools/spec_tool.py generate` instead.

package revision.core.catalogue

import revision.core.catalogue.aqa.aqaBiology
import revision.core.catalogue.edexcel.edexcelBiology
import revision.core.catalogue.ocr.ocrBiology
import revision.core.catalogue.aqa.aqaChemistry
import revision.core.catalogue.edexcel.edexcelChemistry
import revision.core.catalogue.ocr.ocrChemistry
import revision.core.catalogue.aqa.aqaComputerScience
import revision.core.catalogue.ocr.ocrComputerScience
import revision.core.catalogue.aqa.aqaEnglishLanguage
import revision.core.catalogue.aqa.aqaEnglishLiterature
import revision.core.catalogue.aqa.aqaFrench
import revision.core.catalogue.aqa.aqaGeography
import revision.core.catalogue.aqa.aqaHistory
import revision.core.catalogue.aqa.aqaMaths
import revision.core.catalogue.aqa.aqaPhysics
import revision.core.catalogue.edexcel.edexcelPhysics
import revision.core.catalogue.aqa.aqaReligiousStudies

internal val generatedSubjects: List<SpecSubject> = listOf(
    aqaBiology,
    edexcelBiology,
    ocrBiology,
    aqaChemistry,
    edexcelChemistry,
    ocrChemistry,
    aqaComputerScience,
    ocrComputerScience,
    aqaEnglishLanguage,
    aqaEnglishLiterature,
    aqaFrench,
    aqaGeography,
    aqaHistory,
    aqaMaths,
    aqaPhysics,
    edexcelPhysics,
    aqaReligiousStudies,
)
